hub:
  build: ./Hub
  ports:
    - 4444:4444

nodeChrome:
  image: selenium/node-chrome:2.44.0
  links:
    - hub
  ports:
    - 5900
  environment:
    SCREEN_WIDTH: 1280
    SCREEN_HEIGHT: 800
  volumes:
    - /dev/urandom:/dev/random

nodeFirefox:
  image: selenium/node-firefox:2.44.0
  links:
    - hub
  ports:
    - 5900
  environment:
    SCREEN_WIDTH: 1280
    SCREEN_HEIGHT: 800
  volumes:
    - /dev/urandom:/dev/random

