hub:
  build: ./Hub
  ports:
    - 4444:4444

nodeChrome:
  image: selenium/node-chrome-debug:2.45.0
  links:
    - hub
  ports:
    - 5900
  environment:
    SCREEN_WIDTH: 1280
    SCREEN_HEIGHT: 800
  volumes:
    - /dev/urandom:/dev/random

nodeFirefox:
  image: selenium/node-firefox-debug:2.45.0
  links:
    - hub
  ports:
    - 5900
  environment:
    SCREEN_WIDTH: 1280
    SCREEN_HEIGHT: 800
  volumes:
    - /dev/urandom:/dev/random

